### ISSUE TITLE
Vue Client: Unable to login after creating new account

### ISSUE THREAD

**Issue by s-kris** [Rajan/lesspod#12]
**warning (server component):** 
`(sequelize) Warning: Model attributes (email) passed into finder method options of model User, but the options.where object is empty. Did you forget to use options.where?`

**error ( vue client):**
```
POST http://localhost:1234/v1/users/login 422 (Unprocessable Entity)
Login.vue?03db:118 Error: Request failed with status code 422
    at e.exports (spread.js:25)
    at e.exports (spread.js:25)
    at XMLHttpRequest.l.(anonymous function) (https://unpkg.com/axios@0.18.0/dist/axios.min.js:8:3278)
```
node: v8.9.4
npm: 5.6.0
os: OSX 10.13.4
**note:** New account accounted is added to db/users, verified.

**Comment by madguy02** [comment]
Yes same here @Rajan

**Comment by Rajan** [comment]
Can you guys upgrade to node 10.0.0 and npm 6.0.0 and see?

**Comment by Rajan** [comment]
Can you pull it and test? I've added a possible fix. 
On my side, it was working before and after this fix.

**Comment by s-kris** [comment]
pulled and tested. Fix is working!

**Comment by Rajan** [comment]
closing the issue. commit ed0cb3eb0c2ac232e549a3c6782f08a713b9670a
