### ISSUE TITLE
Serverless component not starting

### ISSUE THREAD

**Issue by madguy02** [Rajan/lesspod#3]
while running `node -r dotenv/config index.js`  the terminal throws

```
Error: Cannot find module '.env/config'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at module.js:669:12
    at Array.forEach (native)
    at Function.Module._preloadModules (module.js:668:12)
    at preloadModules (bootstrap_node.js:362:38)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:504:3
```

**Comment by madguy02** [comment]
Is it .env or dotenv? @Rajan

**Comment by Rajan** [comment]
node -r dotenv/config index.js 
It is dotenv and there is an npm module with the same name which is installed for me.
From my package.json:
   "dotenv": "^5.0.1",
    "dotenv-extended": "^2.0.2",

**Comment by madguy02** [comment]
@Rajan  resolved, the npm install is not installing all the required dependencies, which i had to install manually and save it to package.json. The packages i installed manually are - sqlite3, sequelize, morgan, bcrypt, bcrypt-promise, dotenv, and some others. This is weird, :(

**Comment by Rajan** [comment]
I faced the same issues and the packages are there in the package.json. Why do you think this might be happening?

**Comment by madguy02** [comment]
The package.json seems ok, i am not sure why is this occuring, have to look into a bit more, will do it ASAP

**Comment by madguy02** [comment]
#10 this is fixed here
