### ISSUE TITLE
Imageupload should work from editor

### ISSUE THREAD

**Issue by Rajan** [Rajan/lesspod#31]
One should be able to upload an image from quill editor in Newpost.vue and the image should be rendered and saved further. We may need to use a backend which can be firebase in this case.

**Comment by Rajan** [comment]
It works locally and stores as base64. We need to make it work on firebase and store it in the cloud storage when it's in the firebase mode.

**Comment by Rajan** [comment]
Here's the process: https://github.com/NextBoy/vue-quill-editor-upload

**Comment by Rajan** [comment]
In the pipeline:
https://github.com/surmon-china/vue-quill-editor/issues/134
https://github.com/surmon-china/vue-quill-editor/issues/135

**Comment by Rajan** [comment]
@s-kris we've added a handler for image-upload in the quill-editor for pushing the image to firebase and adding it to the editor. You can take a look at ab6ea3b75c70f65be4eea27bc3e710304342bd7a

**Comment by s-kris** [comment]
fixed: a7182f3a8bc851b235899481d208c30ab9cbc311
