### ISSUE TITLE
unable to create a new post in vue client

### ISSUE THREAD

**Issue by s-kris** [Rajan/lesspod#36]
content is always empty and hence the following condition fails.

`if (title.length && content.length) {`

**Comment by Rajan** [comment]
The new post should be created only after there is some data. Clicking on the "New post" menu should only bring up the page. The creation happens when someone clicks on the "Save Post" button.

**Comment by Rajan** [comment]
I noticed that it's not really working locally somehow. Checking it.

**Comment by anurag-git** [comment]
I also tried not working. How to get debug logs. I don't see anything on console.

**Comment by Rajan** [comment]
The problem is that vue data item "content" is replaced with "editor" in my new code. You've not created a branch for this and hence that change has been overwritten.

**Comment by Rajan** [comment]
The problem seems to be with editor binding with quill-editor tag. It is not reflecting in the vue data and hence it is failing.

**Comment by Rajan** [comment]
@anurag-git  I just disabled the Image_Resize options and it works. The problem still lies with the image_resize options with our vue-quill-editor. Hence it is not yet solved.

**Comment by Rajan** [comment]
@s-kris  can you pull  3aa863f the new post should work.

**Comment by s-kris** [comment]
It's working now.

**Comment by Rajan** [comment]
@anurag-git can you help with #30 without breaking newpost?

**Comment by anurag-git** [comment]
@Rajan Let me take new changes and then try. Can you explain what has to be done now, after my fix was not reverted(or not working as expected)

**Comment by Rajan** [comment]
If you look at editorOptions in Newpost.vue, we're having to comment resize options.

```
editorOption: {
        modules: {
          toolbar: [
            [{
              'size': ['small', false, 'large']
            }],
            ['bold', 'italic'],
            [{
              'list': 'ordered'
            }, {
              'list': 'bullet'
            }],
            ['link', 'image', 'video']
          ],
          history: {
            delay: 1000,
            maxStack: 50,
            userOnly: false
          },
          imageDrop: true
          // imageResize: {
          //   displayStyles: {
          //     backgroundColor: 'black',
          //     border: 'none',
          //     color: 'white'
          //   },
          //   modules: ['Resize', 'DisplaySize', 'Toolbar']
          // }
        }
      }
```
Because uncommenting it makes the editor fail. Need to understand 'Why' is this happening (look into ../main.js) and fix it.
