### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [Rajan/lesspod#39]
Good day Sir @Rajan  I am a graphics designer and I am interested in contributing to your project by proposing a logo design which I am going to do as a gift for free here. If you will permit me I will start my design immediately. I have noticed that the project has no logo yet. Thanks and best regards! 

-Tobaloidee

**Comment by Rajan** [comment]
This is great. Kindly proceed. Thank you.

**Comment by Tobaloidee** [comment]
Will work on it and show you here the design asap Sir..Thanks!

**Comment by Tobaloidee** [comment]
Here's my design sir, still open for modifications if you have any

![lesspod-01](https://user-images.githubusercontent.com/36028424/40962873-69a07f22-68d9-11e8-87fc-e82e2ed1ddce.png)

![lesspod-02](https://user-images.githubusercontent.com/36028424/40962882-7061d464-68d9-11e8-987c-93c65f91d68c.png)

**Comment by Rajan** [comment]
These are good but try to make it simple and beautiful. A logo has to be remarkable and memorable both at the same time. I know this is hard. =)

**Comment by Tobaloidee** [comment]
ill edit it and take note of it Sir..

**Comment by Tobaloidee** [comment]
here sir 

![lesspod a-01](https://user-images.githubusercontent.com/36028424/40971359-f465b026-68ef-11e8-9e34-608a4ba3266c.png)

**Comment by Rajan** [comment]
Much better. I really like the top right one. Can you make the pod (internal shape) a little bigger?

**Comment by Tobaloidee** [comment]
I made 3 adjustments Sir

![lesspod b-01](https://user-images.githubusercontent.com/36028424/40971742-2f2974da-68f1-11e8-8e01-e33303dbb759.png)

**Comment by Rajan** [comment]
I like the shape of number 1 and the size of number 3.

- All sides should be of the same thickness.
- The internal shape should be as big as possible (without looking awkward).

**Comment by Tobaloidee** [comment]
![lesspod ef-01](https://user-images.githubusercontent.com/36028424/40973080-7a335208-68f5-11e8-9d38-64bedbf5e07d.png)


I tried one with shadow just to let you see

![lesspod ef-02](https://user-images.githubusercontent.com/36028424/40973107-8e63e81e-68f5-11e8-8d35-7b63cf6837cc.png)

**Comment by Rajan** [comment]
Good stuff. We should remove the tagline because it will be text.

**Comment by Tobaloidee** [comment]
okay Sir, so is it with shadow or without?

**Comment by Tobaloidee** [comment]
yes sir, I will make separate files for them and upload here. SVG and PNG formats. Should i make a PR for the files to be uploaded?

**Comment by Rajan** [comment]
yes. thank you.

**Comment by Rajan** [comment]
Dimensions of round logo: 244 x 244 pixels.
Dimensions of rectangle logo: 147 x 41 pixels.

**Comment by Tobaloidee** [comment]
Sir, I uploaded it all and update the readme with this PR #41 

Thanks so much!
