### ISSUE TITLE
Editpost.vue: pageURL gets overwritten (Firebase)

### ISSUE THREAD

**Issue by Rajan** [Rajan/lesspod#53]
When a menu-post is edited. The pageURL parameter is gone.
Maybe we also need to preserve other parameters.

**Comment by s-kris** [comment]
I din't quite get this, firebase gets updated with same data as localhost.

**Comment by Rajan** [comment]
Update mechanism of Firebase works differently from update mechanism of SQLite. Firebase overwrites the whole records (deleting prior fields) while SQLite preserves other field data. So, we need to provide Firebase with more fields.

**Comment by s-kris** [comment]
Yes. That's why I used 'update' method.

**Comment by Rajan** [comment]
We need to provide all the prior fields to update method in case of Firebase.

**Comment by s-kris** [comment]
Let's get on a call.

**Comment by s-kris** [comment]
d55d15cfc4d2436c0519092f111fe4479b7789a4 
Page.vue is the file that need to be modified. 
Reason: vm.pageurl is empty. modfied the code to reflect changes
