### ISSUE TITLE
Auto Login after registration is broken on the hosted instance

### ISSUE THREAD

**Issue by Rajan** [Rajan/lesspod#60]
It shows navbar without the menu. The token is not being set or something.
<img width="1263" alt="screen shot 2018-06-12 at 4 50 37 pm" src="https://user-images.githubusercontent.com/60307/41287619-eedb3e0c-6e60-11e8-9e8f-1cadc10fad10.png">

**Comment by s-kris** [comment]
fixed: 4126b8bd83fded57ce5e2f7c6313fcd260f963f3
