### ISSUE TITLE
Latest post in Viewpost.vue not implemented in Firebase

### ISSUE THREAD

**Issue by Rajan** [Rajan/lesspod#62]
<img width="989" alt="screen shot 2018-06-13 at 12 04 14 am" src="https://user-images.githubusercontent.com/60307/41309815-5b01ac7e-6e9d-11e8-98d6-0a383b401a03.png">

**Comment by s-kris** [comment]
fixed: 33faa7b235dc4014f6d134c1faeac83ff9df1a94
